Repository ntohq/buefy-next, pull requests merged in 2025-04, with the labels that each got.

#449 Bulma v1 Migration - Deprecated Global Built-in Functions #420
  package-lock.json
  packages/buefy-next/src/scss/components/_checkbox.scss
  packages/buefy-next/src/scss/components/_pagination.scss
  packages/buefy-next/src/scss/components/_switch.scss
  packages/buefy-next/src/scss/utils/_all.scss
  packages/buefy-next/src/scss/utils/_functions.scss
Labels: Bulma v1

#452 Fix Rollup Build Errors
  package-lock.json
  package.json
  packages/buefy-next/rollup.config.mjs
Labels: enhancement

#458 Fix Build TS Definition Warnings
  packages/buefy-next/api-extractor.json
  packages/buefy-next/src/components/dialog/Dialog.vue
  packages/buefy-next/src/components/field/Field.vue
  packages/buefy-next/src/components/icon/Icon.vue
  packages/buefy-next/src/components/image/Image.vue
  packages/buefy-next/src/components/input/Input.vue
  packages/buefy-next/src/components/progress/Progress.vue
  packages/buefy-next/src/components/snackbar/Snackbar.vue
  packages/buefy-next/src/components/steps/Steps.vue
  packages/buefy-next/src/components/switch/Switch.vue
  packages/buefy-next/src/components/table/TableColumn.vue
  packages/buefy-next/src/components/tag/Tag.vue
  packages/buefy-next/src/utils/MessageMixin.ts
  packages/buefy-next/src/utils/ProviderParentMixin.ts
  packages/buefy-next/src/utils/config.ts
  packages/buefy-next/src/utils/helpers.ts
  packages/buefy-next/src/utils/icons.ts
  packages/buefy-next/src/utils/vue-augmentation.ts
  packages/docs/src/pages/extensions/cleavejs/examples/ExFormat.vue
  packages/docs/src/pages/extensions/sortablejs/examples/ExSimple.vue
Labels: documentation, enhancement
